In [ ]:
import torch
print(torch.__version__)

2.0.1+cu118


# Introduction to tensors

## Creating tensors


In [ ]:
torch.tensor(7)

tensor(7)

In [ ]:
vector = torch.tensor([2,3])

In [ ]:
vector.ndim

1

In [ ]:
#MATRIX
MATRIX = torch.tensor([[1,2,3],
                       [7,8,9]])
MATRIX.ndim


2

In [ ]:
Matrix2 = torch.tensor([[2],
                       [7]])
MATRIX*Matrix2

tensor([[ 2,  4,  6],
        [49, 56, 63]])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[[1,2,3],
                        [4,5,6]],
                       [[2,3,4],
                       [3,4,5]]]])
TENSOR.shape

torch.Size([1, 2, 2, 3])

In [ ]:
print(TENSOR.ndim)
print(TENSOR[0][1])

4
tensor([[2, 3, 4],
        [3, 4, 5]])


In [ ]:
TENSOR[0][1][0]

tensor([2, 3, 4])

Random Tensor


In [ ]:
random_tensor = torch.rand(size = (2,3,4))
random_tensor

tensor([[[0.3913, 0.8443, 0.8223, 0.0878],
         [0.7689, 0.7057, 0.1033, 0.5710],
         [0.5743, 0.2732, 0.7361, 0.1762]],

        [[0.6854, 0.8246, 0.8411, 0.4669],
         [0.1882, 0.0374, 0.2811, 0.9815],
         [0.3984, 0.5746, 0.8352, 0.2242]]])

In [ ]:
random_image_tensor = torch.rand(size= (3,224,224)) #color channels(R,G,B),height,width
random_image_tensor.shape, random_image_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [ ]:
r_t = torch.rand(2,4,5)
r_t

tensor([[[0.5742, 0.0138, 0.1530, 0.9912, 0.9913],
         [0.8884, 0.5534, 0.5279, 0.4727, 0.1879],
         [0.9505, 0.4039, 0.1508, 0.0020, 0.1076],
         [0.0389, 0.9209, 0.7325, 0.4206, 0.1091]],

        [[0.8216, 0.3340, 0.9214, 0.1257, 0.3920],
         [0.1803, 0.3369, 0.1506, 0.7171, 0.7205],
         [0.9300, 0.0526, 0.6162, 0.8205, 0.0189],
         [0.2037, 0.4593, 0.0014, 0.8967, 0.8244]]])

In [ ]:
M = torch.rand(2,3)
M

tensor([[0.8541, 0.8722, 0.9233],
        [0.8285, 0.8516, 0.2614]])

In [ ]:
zeroes = torch.zeros(2,1)
zeroes*M

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
range_tensor = torch.arange(start = 1, end = 100, step = 15)
range_tensor

tensor([ 1, 16, 31, 46, 61, 76, 91])

In [ ]:
some_zeros = torch.zeros_like(input = range_tensor)
some_zeros

tensor([0, 0, 0, 0, 0, 0, 0])

#Tensor data types

##Three Big Errors
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on right device


In [ ]:
float32_tensor = torch.tensor([[3.0,6,0,8.0]],
                              dtype = None,
                              device = None,  #'cpu' 'cuda'
                              requires_grad=False)
float32_tensor.dtype, float32_tensor.device

(torch.float32, device(type='cpu'))

In [ ]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([[3., 6., 0., 8.]], dtype=torch.float16)

In [ ]:
tensor = torch.tensor([[1,2,3]])
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([[1, 2, 3]]) * tensor([[1, 2, 3]])
Equals: tensor([[1, 4, 9]])


In [ ]:
#Matrix Multiplication
torch.matmul(tensor,tensor.T)
torch.mm(tensor,tensor.T)

tensor([[14]])

In [ ]:
#Transpose
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
print(tensor_A.shape, tensor_A.T.shape)
tensor_A.T

torch.Size([3, 2]) torch.Size([2, 3])


tensor([[1, 3, 5],
        [2, 4, 6]])

torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.

#Min, Max, Mean, Sum


In [ ]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# mean function requires a tensor of float32
torch.mean(x.type(torch.float32)), (x.type(torch.float32)).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
x.argmax(),x.argmin()

(tensor(9), tensor(0))

In [ ]:
torch.argmax(x),torch.argmin(x)

(tensor(9), tensor(0))

#Reshape, stacking, squeezing and unsqueezing

In [ ]:
x = torch.arange(1,11,1)
x, x.size()

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [ ]:
x_reshaped = x.reshape(1,10)
x_reshaped

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
x_reshaped = x.reshape(10,1)
x_reshaped

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [ ]:
z = x.view(10,1)
z
#Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

#So changing the view changes the original tensor too.

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [ ]:
z[0][0]= 5
#z[:,0] = 5
z,x,x.dtype

(tensor([[ 5],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 torch.int64)

#Stacking

vertical stack : dim 0
horizontal stack: dim 1

In [ ]:
x_stack = torch.stack([x,x,x,x],dim = 1)
x_stack
# dim = 0 default

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

torch.squeeze()- removes all single dimensions from a target tensor


In [ ]:
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

x_squeezed= x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New shape:{x_squeezed.shape}")

previous tensor: tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
previous shape: torch.Size([1, 10])

New Tensor: tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])
New shape:torch.Size([10])


In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor at specific dim
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [ ]:
#torch.permute - rearrange the dimension of a target tensor in a specified error
x_original = torch.rand(224,224,3)

x_permuted = x_original.permute(2,0,1)
print(f"Previous shape: {x_original.shape}")
print(f"Shape after permute: {x_permuted.shape}")

#permute is a view of original so it shares the same address/place in memory

Previous shape: torch.Size([224, 224, 3])
Shape after permute: torch.Size([3, 224, 224])


Indexing

In [ ]:
x = torch.arange(1,10,1).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# You can use ":" to select "all" of a target dimension
x[:,:,1]
print(x[0,:,2])


tensor([3, 6, 9])


#PyTorch tensors & Numpy
Data in numpy to Pytorch Tensor --> torch.from_numpy(ndarray)

PyTorch tensor to Numpy --> torch.Tensor.numpy()

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0) #when converting numpy --> pytorch reflects numpy's default datatype of float64 unless specified otherwise
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibilty (trying to take random out of random )

In [ ]:
# concept of **random seed**
Random_seed = 42
torch.manual_seed(Random_seed)
tensor_a = torch.rand(3,4)

torch.manual_seed(Random_seed)
tensor_b = torch.rand(3,4)
print(tensor_a)
print(tensor_b)
print(tensor_a == tensor_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Check for GPU access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

False

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count number of devices
torch.cuda.device_count()

0

#Putting tensors (and models) on GPU

In [ ]:
import torch
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Moving tensor back to cpu


In [ ]:
#cant copy tensors on GPU to numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])